# Generated by Django 3.0.6 on 2020-05-29 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200528_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raspisaniepodniam',
            options={'verbose_name': 'Расписание на неделю', 'verbose_name_plural': 'Расписание на неделю '},
        ),
        migrations.AddField(
            model_name='spisokvosproizvedenia',
            name='filtruemoe_dt_po',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Фильтрумое дата время по'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spisokvosproizvedenia',
            name='filtruemoe_dt_s',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Фильтрумое дата время с'),
            preserve_default=False,
        ),
    ]
