# Generated by Django 3.1 on 2020-08-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200529_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nabormedia',
            name='recomendovania_prodolzitelnost',
        ),
        migrations.RemoveField(
            model_name='nabormedia',
            name='skorost_perelistivanie_slaida',
        ),
        migrations.RemoveField(
            model_name='raspisaniepodniam',
            name='zvuk',
        ),
        migrations.AlterField(
            model_name='media',
            name='tip_media',
            field=models.CharField(choices=[('Аудио', 'Аудио')], max_length=255, verbose_name='Тип медиа'),
        ),
    ]
